from requests_html import AsyncHTMLSession

session = AsyncHTMLSession()

r = await session.get("https///www.reddit.com/")
print(r.status_code)        # 200

divs = r.html.find('div')
links = r.html.find('a')
urls = r.html.absolute_links         # 'absolute_links' is an attribute

await r.html.arender()
# It will download and install Chromium (if you don't have it already!)
# "Chromium is a program that behaves like a browser but has no graphical interface

new_divs = r.html.find('div')       # greater length now
new_links = r.html.find('a')        # greater length now
new_urls = r.html.absolute_links    # greater length now

# set1.difference(set2)
# -> it returns only those elements of set1 that are not contained in set2

new_urls.difference(urls)
# the response are all the URLs that were generated by Javascript :)

session.close()
